### ISSUE TITLE
Site Owner Task #2

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis-buddies#2]
As a **site owner**, I can **create the Django project and app** so that **I can set up the database**

### Acceptance Criteria:
1.  Create a directory for the Django project
2.  Create the TennisBuddies app

### Tasks
- [ ]  Create the Django project TennisBuddies
- [ ] Create the TennisBuddies app (buddy)
- [ ] Add the buddy app to hte Installed_apps in settings.py
- [ ] Migrate the changes to the database
- [ ] Run server to check if all is working
