### ISSUE TITLE
Dev Task #6 - Create Database models from ERD

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis-buddies#6]
As a **developer**, I can **set up my models.py files** so that I can **create my database tables**

### Acceptance Criteria:

1.  Successfully create TennisBudies ERD.
2.  Create apps for each model and add models to models.py
3.  Import revelavant Django/Cloudinary models.

### Tasks:

- [ ] Import relevant Django/Cloudinary Models
- [ ] Add user/buddy model
- [ ] Add booking model
- [ ] Add event model
- [ ] Add court model
- [ ] Add club model
